# Snakemake workflow for the analysis of ChIP-seq data
#
# Author: Maurits Evers
# License: GPLv3
# Original date: 14-10-2016
# Last changed: 23-10-2016

from os.path import join
import re
import glob

def message(mes):
  sys.stderr.write("|--- " + mes + "\n")

#######################################################
################## Global variables ###################
#######################################################

# Config files
configfile: "config.yaml"

# Working directory
workdir: config["basedir"]

#######################################################
######################### Targets #####################
#######################################################

# Reference sequence
REF = join(config["refdir"], config["refseq"]["id"], config["refseq"]["filename"])

# bowtie2 index
IDX = expand(re.sub("fa", "{idx}.bt2l", REF), idx = range(1,5))

#for smp in ALL_BAM:
#    message("Sample " + smp + " will be created")

#######################################################
###################### Includes #######################
#######################################################

#include: "rules/mhs_data.rules"
include: "rules/reference.rules"


#######################################################
######################## Rules ########################
#######################################################

# Input fastq files
rule all:
    input:
        IDX
